---
# roles/nginx/handlers/main.yml

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: _systemd_active.stat.exists

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: _systemd_active.stat.exists
